---
title: "Metal clustering"
author: "Bindoff, A."
output: html_document
---

`r Sys.time()`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, message = F, warning = F}
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(latex2exp)
library(Rtsne)
library(vegan)
mciMean <- function(x){
  return(setNames(c(round(mean(x), 3), round(ciMean(x), 3)), c("mean", "lwr", "upr")))
}


df <- read_csv("neuro_metal_nfl.csv", trim_ws = T)
names(df) <- gsub("\\b\\d+\\b", "", names(df)) # remove numbers
names(df) <- gsub("  ", "", names(df)) # remove extraneous blanks
names(df)[1:6] <- c("id", "age", "strain", "region", "sample", "dilution")
df$region[df$region == "Siatic nerve"] <- "Sciatic nerve"
df$id <- factor(df$id)
df$age <- factor(df$age)
df$strain <- gsub("[[:punct:]]", "", df$strain)
df$strain <- gsub("^WT AP.*", "WT_APPPS1", as.character(df$strain))
df$strain <- factor(df$strain)
df$region <- factor(df$region)

sel <- c(1,2,3,4,5,9,10,11,13,14,17,18,21,22,23,24)

df <- dplyr::select(df, sel) %>%# remove metals at or below detection limit
    filter(strain == "WT" | strain == "NFL", age == 5 | age == 22) %>% filter(id != 15) # nfl id == 15 was 19mo
df$strain <- factor(df$strain, levels = c("WT", "NFL"), labels = c("WT", "NFL-KO"))
df$age <- factor(df$age, levels = c(5, 22))
df <- na.omit(df)
df$Cu[df$Cu >= 320] <- NA 


`%nin%` <- Negate(`%in%`)

df <- dplyr::filter(df, id %nin% c("238", "3183", "161470"))

pal <- scico::scico(n = 6, palette = 'batlow')

```

tSNE 'discovers' clusters which clearly delineate into brain regions when metals are scaled irrespective of region or age.  

```{r}
set.seed(77)
A <- sapply(6:16, function(x) scale(df[, x]))
A[] <- apply(A, 2, function(x) ifelse(is.na(x), 0 , x))

m1 <- Rtsne(A, dim = 2, perplexity = 10, max_iter = 6000, theta = 0.1)

d <- data.frame(y1 = m1$Y[, 1], 
                y2 = m1$Y[, 2],
                strain = df$strain,
                id = df$id,
                region = df$region,
                age = df$age,
                strain = df$strain)

ggplot(d, aes(x = y1, y = y2, colour = region)) +
  geom_point() +
  scico::scale_color_scico_d(palette = "batlow") +
  theme_minimal()

```

Clusters start to form around genotypes when data are grouped by region and age then scaled.  

```{r}
metals <- c("Na",
            "Mg",
            "Al",
            "K",
            "Ca",
            "Mn",
            "Fe",
            "Cu",
            "Zn",
            "Se",
            "Rb")
metals <- names(df[, 6:16])
B <- filter(df) %>%
  group_by(region, age) %>%
  mutate(Na = scale(Na),
         Mg = scale(Mg),
         Al = scale(Al),
         K = scale(K), 
         Ca = scale(Ca),
         Mn = scale(Mn),
         Fe = scale(Fe),
         Cu = scale(Cu),
         Zn = scale(Zn),
         Se = scale(Se),
         Rb = scale(Rb)) %>%
  ungroup() 

A <- select(B, metals)
A[] <- apply(A, 2, function(x) ifelse(is.na(x), 0 , x))

set.seed(888)
m1 <- Rtsne(A, dim = 2,
            perplexity = 7,
            max_iter = 10000, 
            theta = 0.05)

# make a data frame that assigns an attribute one 
# column/taxa at a time
foo <- function(x){
  g <- as.matrix(B[, x])
  B %>% mutate(attr = g,
               Metal = x,
                    y1 = m1$Y[, 1],
                    y2 = m1$Y[, 2])
  
}

k <- lapply(metals, foo)
k <- dplyr::bind_rows(k)

p1 <- ggplot(k, aes(x = y1, y = y2, colour = strain, size = attr, alpha = col, frame = Metal, scale = 1.5)) +
  geom_point() +
  scale_colour_manual(values = pal[c(3, 5)]) +
  theme_minimal()

plotly::ggplotly(p1)

```

  
```{r echo = TRUE}
set.seed(42)

B <- filter(df) %>%
  group_by(region, age) %>%
  mutate(Na = scale(Na),
         Mg = scale(Mg),
         Al = scale(Al),
         K = scale(K), 
         Ca = scale(Ca),
         Mn = scale(Mn),
         Fe = scale(Fe),
         Cu = scale(Cu),
         Zn = scale(Zn),
         Se = scale(Se),
         Rb = scale(Rb)) %>%
  ungroup() 

A <- select(B, metals)
A[] <- apply(A, 2, function(x) ifelse(is.na(x), 0 , x))


# sort metals using Classical Multidimensional Scaling
D <- dist(A, method = "euclidean")
m3 <- cmdscale(D, k = 1)

tD <- dist(t(A), method = "euclidean")
m4 <- cmdscale(tD, k = 1)

# arrange samples and taxa by ordination above
B1 <- data.frame(B,
                 m3.Y = m3[,1]) %>%
  arrange(strain) %>%  # arrange samples
  mutate(sample = factor(sample, sample)) %>%
  reshape2::melt(id.vars = c("id", "age", "strain", "region", "sample", "m3.Y"))

mets <- tibble::rownames_to_column(data.frame(m4)) %>% arrange(m4)
B1$variable <- factor(B1$variable, mets$rowname)

# plot a heatmap
ggplot(B1, aes(x = variable, y = sample,
               fill = value)) +
  geom_tile() +
  scico::scale_fill_scico(palette = "vik", name = "Abundance (z)") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6, colour = B1$strain)) +
  ylab("Sample (red NFL-KO, black WT)") +
  xlab("Metal")

```